--------------------------------------------------------
-- CUSTOMER PROJECT ANALYSIS WITH SQL QUERIES ----------
--------------------------------------------------------

use projects;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(amount) as revenue
from df
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,amount 
from df
where discount_used = 'Yes' and amount >= (select AVG(amount) from df);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
    item,
    ROUND(AVG(CAST(rating AS DECIMAL(3,2))), 2) AS Average_Product_Rating
FROM df
GROUP BY item
ORDER BY AVG(rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(amount),2)
from df
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item,
       ROUND(100.0 * SUM(CASE WHEN discount_used = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM df
GROUP BY item
ORDER BY discount_rate DESC
LIMIT 5;


-- Q6. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, total_orders,
CASE 
    WHEN total_orders = 1 THEN 'New'
    WHEN total_orders BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM df)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q7. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item,
           COUNT(customer_id) AS total_order,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM df
    GROUP BY category, item
)
SELECT item_rank,category, item, total_order
FROM item_counts
WHERE item_rank <=3;
 
-- Q8. What is the revenue contribution of each age group? 
SELECT 
    age,
    SUM(amount) AS total_revenue
FROM df
GROUP BY age
ORDER BY total_revenue desc;

-- Q9.Which customers contribute the most to overall revenue, and what common
-- characteristics do they share?

SELECT
    customer_id,
    SUM(amount) AS total_revenue
FROM df
GROUP BY customer_id
ORDER BY total_revenue DESC;

-- Q10.Does discount usage lead to higher long-term customer value or only short-term sales?

SELECT
    discount_used,
    COUNT(DISTINCT customer_id) AS customers,
    ROUND(AVG(total_orders), 2) AS avg_total_orders,
    ROUND(AVG(amount), 2) AS avg_order_value,
    ROUND(AVG(total_orders * amount), 2) AS avg_lifetime_value,
    ROUND(AVG(rating), 2) AS avg_rating
FROM df
GROUP BY discount_used;

-- Q11. Which product categories attract many customers but contribute relatively low revenue?

SELECT
    category,
    COUNT(DISTINCT customer_id) AS total_customers,
    COUNT(*) AS total_orders,
    SUM(amount) AS total_revenue,
    ROUND(AVG(amount), 2) AS avg_order_value
FROM df
GROUP BY category
ORDER BY total_customers DESC;

-- Q12. Are there products with high ratings but low sales, indicating under-marketing
-- opportunities?

WITH product_metrics AS (
    SELECT item,COUNT(*) AS orders,SUM(amount) AS revenue,AVG(rating) AS avg_rating
    FROM df
    GROUP BY item
)
SELECT item,orders,revenue,ROUND(avg_rating, 2) AS avg_rating
FROM product_metrics
WHERE avg_rating > (SELECT AVG(avg_rating) FROM product_metrics)
  AND revenue < (SELECT AVG(revenue) FROM product_metrics)
ORDER BY avg_rating DESC;

-- Q13. What seasonal trends exist in customer spending and product preferences?

-- Category preference by season
SELECT
    season,
    category,
    COUNT(*) AS orders
FROM df
GROUP BY season, category
ORDER BY season, orders DESC;

-- Most popular item in each season

WITH ranked_items AS (
    SELECT
        season,
        item,
        COUNT(*) AS order_count,
        RANK() OVER (PARTITION BY season ORDER BY COUNT(*) DESC) AS rnk
    FROM df
    GROUP BY season, item
)
SELECT season, item, order_count
FROM ranked_items
WHERE rnk = 1;

-- combine
SELECT
    season,
    category,
    SUM(amount) AS revenue
FROM df
GROUP BY season, category
ORDER BY season, revenue DESC;


-- Q14. Which products perform well consistently across all seasons?

SELECT
    item,
    COUNT(DISTINCT season) AS seasons_covered,
    COUNT(*) AS total_orders,
    SUM(amount) AS total_revenue,
    ROUND(AVG(rating), 2) AS avg_rating
FROM df
GROUP BY item
HAVING COUNT(DISTINCT season) = (
    SELECT COUNT(DISTINCT season) FROM df
)
ORDER BY total_revenue DESC;


-- Q15.  How does shipping type impact customer satisfaction and repeat purchasing behavior?

SELECT
    shipping_type,
    COUNT(*) AS total_orders,
    ROUND(AVG(rating), 2) AS avg_rating
FROM df
GROUP BY shipping_type
ORDER BY avg_rating DESC;

-- Combined view
SELECT
    shipping_type,
    COUNT(DISTINCT customer_id) AS customers,
    ROUND(AVG(rating), 2) AS avg_rating,
    ROUND(AVG(total_orders), 2) AS avg_repeat_orders
FROM df
GROUP BY shipping_type
ORDER BY avg_rating DESC, avg_repeat_orders DESC;

-- Q16. Are there locations where operational choices (shipping type or payment method)
-- significantly impact customer satisfaction and order frequency?

-- Location × Shipping performance

SELECT
    location,
    shipping_type,
    COUNT(DISTINCT customer_id) AS customers,
    ROUND(AVG(rating), 2) AS avg_rating,
    ROUND(AVG(total_orders), 2) AS avg_repeat_orders
FROM df
GROUP BY location, shipping_type
HAVING COUNT(DISTINCT customer_id) >= 2
ORDER BY location, avg_rating DESC;

-- Location × Payment performance
SELECT
    location,
    payment_method,
    COUNT(DISTINCT customer_id) AS customers,
    ROUND(AVG(rating), 2) AS avg_rating,
    ROUND(AVG(total_orders), 2) AS avg_repeat_orders
FROM df
GROUP BY location, payment_method
HAVING COUNT(DISTINCT customer_id) >= 2
ORDER BY location, avg_rating DESC;



